// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqpulnekszupteusnpgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcHVsbmVrc3p1cHRldXNucGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODY1MzEsImV4cCI6MjA1OTk2MjUzMX0.E_-BGwHk2cMfQbuDTEJEUhCjfPhW2s9uI-l_0tmfzZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);